import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/blockchain/config";
import BlockchainProviders from "@/blockchain/BlockchainProviders";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blockchain Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookie = headers().get('cookie');
  const initialState = cookieToInitialState(getConfig(), cookie)
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <BlockchainProviders initialState={initialState}>
          <Header />
          {children}
          <Footer />
          <Toaster richColors position="top-center" duration={2000} />
        </BlockchainProviders>
      </body>
    </html>
  );
}
